---
  student: examplestagestudents.neols.com
  teacher: examplestageteachers.neols.com
  principal: examplestageprincipal.neols.com
  admin:  examplestageadmin.neols.com
  board: examplestageboard.neols.com
  env: stage
