---
  student: exampledevstudents.neols.com
  teacher: exampledevteachers.neols.com
  principal: exampledevprincipal.neols.com
  admin:  exampledevadmin.neols.com
  board: exampledevboard.neols.com
  env: development
