---
  student: exampleexampledevstudents.neols.com
  teacher: exampledevteachers.neols.com
  principal: exampledevprincipal.neols.com
  admin:  exampledevadmin.neols.com
  board: exampledevboard.neols.com
